### ISSUE TITLE
floating pane doesn't show up

### ISSUE THREAD

**Issue by Morganwan90** [Stardusten/ob-table-enhancer#96]
version 1.4.1
the floating pane doesn't show up when right click

![截图_20230731150233](https://github.com/Stardusten/ob-table-enhancer/assets/61633409/dd205dc9-f0d8-49ce-99f6-c3919871f860)

**Comment by aikruger** [comment]
Same here, incredibly useful add-in otherwise. I think it went with Obsidian v 1.4.2

**Comment by ChenxyLindsay** [comment]
same here

**Comment by chenxin0397** [comment]
1.4.5 same here

**Comment by loveminimal** [comment]
1.4.5 the same error 😂

**Comment by Ohxbong** [comment]
1.4.5 the same error...

**Comment by Xelbayria** [comment]
I am using Table Enhancer `v0.5.10`  & Obsidian `v1.4.5` with the same problem 

what's going on?  the problem is I cannot find 
> A: Make sure "Settings - Appearance - Native menus" is DISABLED!

**Comment by itangqiao** [comment]
+1

**Comment by xjtusjtu** [comment]
+1

**Comment by 9527dong** [comment]
+1

**Comment by Guido-Hwang** [comment]
+1

**Comment by daxiass** [comment]
1.4.5   +1

god please

**Comment by UnknowSelf** [comment]
1.4.12 +1

**Comment by ghost** [comment]
1.4.12 +1

**Comment by GedRelay** [comment]
could someone fix this?

**Comment by WalkLater** [comment]
version: 1.4.14
same problem

**Comment by avraam-inside** [comment]
+1 
could someone fix this?

**Comment by zhaihao** [comment]
@avraam-inside test with https://github.com/Stardusten/ob-table-enhancer/pull/98
@Stardusten please review https://github.com/Stardusten/ob-table-enhancer/pull/98

**Comment by C1og** [comment]
> @zhaihao 

请问可以提供编译后的js代码段吗？

这段js代码无效
```js
    this.registerEvent(this.app.workspace.on("layout-change", function () {
      const view = this.app.workspace.getActiveViewOfType(MarkdownView).contentEl;
      view.querySelectorAll("div.cm-embed-block.cm-table-widget").forEach(function (el) {
        el.attributes.getNamedItem("contenteditable").value = "true";
      });
    }));
```

**Comment by avraam-inside** [comment]
I tried both code block options - it doesn't work(

@zhaihao - I stuck your piece of code into compiled "main.js" file of the plugin - but the plugin simply does not start because of the line "view: HTMLElement". Without it - plugin runs, but doesn't work.

@Yzzzzzzzzzzzz Your option runs the plugin, but contenteditable is still "false"
![image](https://github.com/Stardusten/ob-table-enhancer/assets/52919010/69f7fef0-3126-4d34-873e-2b16314d07d5)

**Comment by avraam-inside** [comment]
It is not possible to get into this event through debugger - do you have any ideas why it does not work when the plugin is launched?

**Comment by zhaihao** [comment]
> I tried both code block options - it doesn't work(
> 
> @zhaihao - I stuck your piece of code into compiled "main.js" file of the plugin - but the plugin simply does not start because of the line "view: HTMLElement". Without it - plugin runs, but doesn't work.
> 
> @Yzzzzzzzzzzzz Your option runs the plugin, but contenteditable is still "false" ![image](https://user-images.githubusercontent.com/52919010/273445085-69f7fef0-3126-4d34-873e-2b16314d07d5.png)

ignore ts compile error
// @ts-ignore

**Comment by zhaihao** [comment]
please try to  replace main.js and reload obsidian

@Yzzzzzzzzzzzz 
@avraam-inside 

[main.js.zip](https://github.com/Stardusten/ob-table-enhancer/files/12840803/main.js.zip)

**Comment by Xelbayria** [comment]
I could help out with running tests on the new code to see if it works or not. let me know.

**Comment by Stardusten** [comment]
Fixed in the latest release https://github.com/Stardusten/ob-table-enhancer/releases/tag/0.5.11. Big thanks to @zhaihao

**Comment by avraam-inside** [comment]
@Stardusten 

Yes, but what have you released?) We have been in correspondence here above - no solution has been found, and the proposed ones do not work. I downloaded the release - still hanging contenteditable = false

![image](https://github.com/Stardusten/ob-table-enhancer/assets/52919010/33cda1e7-8664-42ec-8fb6-ebd1ffe35bad)

**Comment by Xelbayria** [comment]
☝️ Can confirm this on my side. Having the same problem.

**Comment by Stardusten** [comment]
> ☝️ Can confirm this on my side. Having the same problem.



> @Stardusten
> 
> Yes, but what have you released?) We have been in correspondence here above - no solution has been found, and the proposed ones do not work. I downloaded the release - still hanging contenteditable = false
> 
> ![image](https://user-images.githubusercontent.com/52919010/273612757-33cda1e7-8664-42ec-8fb6-ebd1ffe35bad.png)

My bad. My current workaround doesn't work all the time. I still need some time to figure out how to fix it.

**Comment by Xelbayria** [comment]
@Stardusten 
No worries. Take your time. The problem is a challenge to overcome. Again, let me know when your fix is ready for testing so I can test it on my side.

**Comment by zhaihao** [comment]
> > ☝️ Can confirm this on my side. Having the same problem.
> 
> > @Stardusten
> > Yes, but what have you released?) We have been in correspondence here above - no solution has been found, and the proposed ones do not work. I downloaded the release - still hanging contenteditable = false
> > ![image](https://user-images.githubusercontent.com/52919010/273612757-33cda1e7-8664-42ec-8fb6-ebd1ffe35bad.png)
> 
> My bad. My current workaround doesn't work all the time. I still need some time to figure out how to fix it.

@Stardusten 
"layout-change" event only works when we change from reading view to living view. So, if we click the "edit this block" button, the DOM will be re-rendered, and contenteditable will be set to false again. I can't find any API for this event.
The "editor-change" event maybe work well but has poor performance.

**Comment by Stardusten** [comment]
> > > ☝️ Can confirm this on my side. Having the same problem.
> > 
> > 
> > > @Stardusten
> > > Yes, but what have you released?) We have been in correspondence here above - no solution has been found, and the proposed ones do not work. I downloaded the release - still hanging contenteditable = false
> > > ![image](https://user-images.githubusercontent.com/52919010/273612757-33cda1e7-8664-42ec-8fb6-ebd1ffe35bad.png)
> > 
> > 
> > My bad. My current workaround doesn't work all the time. I still need some time to figure out how to fix it.
> 
> @Stardusten "layout-change" event only works when we change from reading view to living view. So, if we click the "edit this block" button, the DOM will be re-rendered, and contenteditable will be set to false again. I can't find any API for this event. The "editor-change" event maybe work well but has poor performance.

I think pop out a menu when click a table cell would be better. But that may take some times.

**Comment by Stardusten** [comment]
The official team is already working on a table editor, so I'm not sure if it's worth investing too much time into this.

**Comment by Xelbayria** [comment]
> The official team is already working on a table editor, so I'm not sure if it's worth investing too much time into this.

@Stardusten 
Is the official name "Table Editor" or a different name? I would like to try it out to provide feedback if I can be of any help. 
If there is a better alternative table plugin than this, then you can give up on this plugin. I hope it will be a better one than this plugin.

**Comment by avraam-inside** [comment]
> The official team is already working on a table editor, so I'm not sure if it's worth investing too much time into this.

On the one hand, yes, they work, on the other, I know 4+ plugins for working with tables with different implementations, and yours is the best) What core-team will do still needs to be seen))) And they have a lot of tasks)

If it's not difficult, I would like to fix contenteditable. If it's difficult, it's probably worth looking at the creation of the core team first

**Comment by chenxin0397** [comment]
In fact, I have found that this plugin always affects the two typewriter mode plugins. Every time I want to use the typewriter mode plugin, I need to turn off this plugin. I wonder if this discovery would be helpful to the author?

**Comment by chenxin0397** [comment]
In fact, I have found that this plugin always affects the two typewriter mode plugins. Every time I want to use the typewriter mode plugin, I need to turn off this plugin. I wonder if this discovery would be helpful to the author?

**Comment by xavierington** [comment]
hey everyone! i think i found a temporary fix. if you "crtl + e" twice, and then try to right click, the pane should show up. You will need to do this every time you use a function in the pane. this seems to be the best way to get it to pop up imo. not sure if there is a token in this temporary solution.

**Comment by xavierington** [comment]
> hey everyone! i think i found a temporary fix. if you "crtl + e" twice, and then try to right click, the pane should show up. You will need to do this every time you use a function in the pane. this seems to be the best way to get it to pop up imo. not sure if there is a token in this temporary solution.

note: i found your cursor also needs to be on a blank line. thanks!

**Comment by WalkLater** [comment]
> > hey everyone! i think i found a temporary fix. if you "crtl + e" twice, and then try to right click, the pane should show up. You will need to do this every time you use a function in the pane. this seems to be the best way to get it to pop up imo. not sure if there is a token in this temporary solution.
> 
> note: i found your cursor also needs to be on a blank line. thanks!

obsidian version: v1.4.16
plugin version: latest

I tried this but failed. I moved my cursor in different positions, but it just do not show up. I guass it is because some other plugins affect its function.

**Comment by ElynnaChuang** [comment]
I had the same problem and it was solved by turning off the plugin "Advanced Tables" , so there may be a conflict between these two plugins ?🤔

**Comment by aikruger** [comment]
Seems obsidian 1.5.0 has most of this functionality now built in. Still preferred this one though
